"""multi-tenant foundation

Revision ID: 0002_multi_tenant
Revises: 0001_baseline
Create Date: 2026-06-15 23:47:14.623357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_multi_tenant'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_key'), ['key'], unique=True)

    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('whatsapp_phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('notify_channel', sa.String(length=16), nullable=False),
    sa.Column('notify_target', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_whatsapp_phone_number_id'), ['whatsapp_phone_number_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenants_workflow_id'), ['workflow_id'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_node_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('answers', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_conversations_tenant_id', 'tenants', ['tenant_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversations_tenant_id'))
        batch_op.drop_column('answers')
        batch_op.drop_column('current_node_id')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_tenants_whatsapp_phone_number_id'))
        batch_op.drop_index(batch_op.f('ix_tenants_active'))

    op.drop_table('tenants')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_key'))

    op.drop_table('workflows')
    # ### end Alembic commands ###
